= Supernaut.FX Sample Maven Project

image:https://github.com/SupernautApp/supernaut-fx-sample-maven/actions/workflows/maven.yml/badge.svg["Build Status", link="https://github.com/SupernautApp/supernaut-fx-sample-maven/actions/workflows/maven.yml"] image:https://github.com/SupernautApp/supernaut-fx-sample-maven/actions/workflows/graalvm.yml/badge.svg["Build Status", link="https://github.com/SupernautApp/supernaut-fx-sample-maven/actions/workflows/graalvm.yml"]

== Overview

A sample/starter project that uses the Maven build system. It uses the https://github.com/openjfx/javafx-maven-plugin[JavaFX Plugin] to build and/or run a JavaFX JAR/app and the https://github.com/gluonhq/gluonfx-gradle-plugin[GluonFX Plugin] to build and run a GraalVM native-image.

NOTE:: Building a native package with `jpackage` is not yet supported with Maven. (See https://github.com/SupernautApp/supernaut-fx-sample-maven/issues/2[Issue #2].) It is supported with Gradle, however. See the https://github.com/SupernautApp/supernaut-fx-sample-gradle[Supernaut.FX Sample Gradle Project] for an example. Building a `jlink` image however, is supported.

== Cloning from Github

. `git clone git@github.com:SupernautApp/supernaut-fx-sample-maven.git`
. `cd supernaut-fx-sample-maven`

== Building with the JDK

=== Setup

. Install JDK 11 or later. (JDK 17 is recommended)
. Install Maven. (Maven 3.8.1 or later is recommended)

=== Build Instructions

To compile and test:

* `mvn verify`

or, to run the app:

* `mvn javafx:run`

To run the `jlink`ed app:

* `./target/image/bin/hellofx`

== Building with GraalVM and Gluon

=== Setup

. Install Graal VM `java17` version 22.0.0.2 or later(Latest GraalVM JDK 17)
. `gu install native-image`
. Set `GRAALVM_HOME` environment variable
. Install Maven. (Maven 3.8.1 or later is recommended)

If you are building a GraalVM native image with GluonFX you may need to install additional software (depending upon your platform) see the https://docs.gluonhq.com/[Gluon Documentation] for info.

=== Building a Native Image

To build:

* `mvn gluonfx:build`

or, to run:

* `mvn gluonfx:build gluonfx:nativerun`

or, to build a packaged application:

* `mvn -Pdesktop gluonfx:build gluonfx:package`

The packaged application will be in `target/gluonfx/<platform>/`

