= Supernaut.FX Sample Maven Project

image:https://github.com/SupernautApp/supernaut-fx-sample-maven/actions/workflows/maven.yml/badge.svg["Build Status", link="https://github.com/SupernautApp/supernaut-fx-sample-maven/actions/workflows/maven.yml"] image:https://github.com/SupernautApp/supernaut-fx-sample-maven/actions/workflows/graalvm.yml/badge.svg["Build Status", link="https://github.com/SupernautApp/supernaut-fx-sample-maven/actions/workflows/graalvm.yml"]

== Overview

A sample/starter project that uses the Maven build system. It uses the https://github.com/openjfx/javafx-maven-plugin[JavaFX Plugin] to build and/or run a JavaFX JAR/app and the https://github.com/gluonhq/gluonfx-gradle-plugin[GluonFX Plugin] to build and run a GraalVM native-image.

NOTE:: Building a native package with `jlink`/`jpackage` is not supported with Maven at this time. (See https://github.com/SupernautApp/supernaut-fx-sample-maven/issues/1[Issue #1].) It is supported with Gradle, however. See the https://github.com/SupernautApp/supernaut-fx-sample-gradle[Supernaut.FX Sample Gradle Project] for an example.

== Cloning from Github

. `git clone git@github.com:SupernautApp/supernaut-fx-sample-maven.git`
. `cd supernaut-fx-sample-maven`

== Building with the JDK

=== Setup

. Install JDK 11 or later. (JDK 17 is recommended)
. Install Maven. (Maven 3.6 or later is recommended)

=== Build Instructions

To compile and test:

* `mvn verify`

or, to run the app:

* `mvn javafx:run`


== Building with GraalVM and Gluon

=== Setup

. Install Graal VM 21.2.0.java11 (Latest GraalVM JDK 11)
. `gu install native-image`
. Set `GRAALVM_HOME` environment variable
. Install Maven. (Maven 3.6 or later is recommended)

If you are building a GraalVM native image with GluonFX you may need to install additional software (depending upon your platform) see the https://docs.gluonhq.com/[Gluon Documentation] for info.

=== Building a Native Image

To build:

* `mvn gluonfx:build`

or, to run:

* `mvn gluonfx:build gluonfx:nativerun`

