name: Maven GraalVM + Gluon Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        # These parameters aren't currently used with gluonhq/setup-graalvm
        java: ['java17']
        graalvm: [ '22.0.0.2' ]
        gu-binary: [gu]
        include:
          - os: windows-latest
            java: 'java17'
            graalvm: '22.0.0.2'
            gu-binary: gu.cmd
      fail-fast: false
    name: ${{ matrix.os }} GraalVM + Gluon
    steps:
      - name: Git checkout
        uses: actions/checkout@v1

      - name: Setup Gluon's GraalVM
        uses: gluonhq/setup-graalvm@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: If Linux, apt-get update
        if: runner.os == 'Linux'
        run: sudo apt-get update

      - name: If Linux, install Linux dependencies
        if: runner.os == 'Linux'
        run: sudo apt install libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev libgtk-3-dev libpango1.0-dev libxtst-dev

      - name: If Windows, add msbuild to PATH
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v1.0.2

      - name: If Windows, Visual Studio shell
        if: runner.os == 'Windows'
        uses: egor-tensin/vs-shell@v1

      - name: Make staging directory
        run: mkdir staging

      - name: Build with Maven and Gluon Plugin
        run: mvn -Pdesktop verify gluonfx:build gluonfx:package

      - name: If macOS, copy Mac native image to staging
        if: runner.os == 'macOS'
        run: cp -r target/gluonfx/x86_64-darwin/SupernautFXHello* staging

      - name: If Windows, copy Windows native image to staging
        if: runner.os == 'Windows'
        run: cp -r target/gluonfx/x86_64-windows/SupernautFXHello.exe staging

      - name: If Linux, copy Linux native image to staging
        if: runner.os == 'Linux'
        run: cp -r target/gluonfx/x86_64-linux/SupernautFXHello** staging

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: SupernautFX Hello ${{ runner.os }} Package
          path: staging